### ISSUE TITLE
License under the MIT license.

### ISSUE THREAD

**Issue by elifoster** [elifoster/HeaderCount#5]
Xbony is terrible and demands that I do this on GitHub so he can't fuck me over or something.

MIT relicense consent:
- [x] @Alexia consented on IRC
- [x] @xbony2 do you consent here on GitHub instead of IRC to prove that you are not a phony ass bitch?

**Comment by xbony2** [comment]
I [wrote it down](https://imgur.com/RpFZfyc), therefor by bony-defying logic it must be real.
